# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:
  datasource:
    username: root
    password:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: ZDgxM2MyNzRlMmEwY2NiYTg3NDJlN2YzMGQwYjFiZTdiYWRkOTNhM2QwZmZjMTQxZjNjYjA0ZmM2YzQ4OGU5NTg1N2QxYzE0MGQyMGU0ZmE0NDAzMGNjMmYzYTJlMjE4ZDNmNjI3Zjg3NmM5MjMzOTMzZTdiZTgyZjIzNjg5OGI=
