package com.paragon.project1.domain;

import static com.paragon.project1.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class CustomerOrderAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomerOrderAllPropertiesEquals(CustomerOrder expected, CustomerOrder actual) {
        assertCustomerOrderAutoGeneratedPropertiesEquals(expected, actual);
        assertCustomerOrderAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomerOrderAllUpdatablePropertiesEquals(CustomerOrder expected, CustomerOrder actual) {
        assertCustomerOrderUpdatableFieldsEquals(expected, actual);
        assertCustomerOrderUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomerOrderAutoGeneratedPropertiesEquals(CustomerOrder expected, CustomerOrder actual) {
        assertThat(actual)
            .as("Verify CustomerOrder auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomerOrderUpdatableFieldsEquals(CustomerOrder expected, CustomerOrder actual) {
        assertThat(actual)
            .as("Verify CustomerOrder relevant properties")
            .satisfies(a -> assertThat(a.getPlacedDate()).as("check placedDate").isEqualTo(expected.getPlacedDate()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a ->
                assertThat(a.getTotalAmount())
                    .as("check totalAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getTotalAmount())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomerOrderUpdatableRelationshipsEquals(CustomerOrder expected, CustomerOrder actual) {
        assertThat(actual)
            .as("Verify CustomerOrder relationships")
            .satisfies(a -> assertThat(a.getShippingAddress()).as("check shippingAddress").isEqualTo(expected.getShippingAddress()))
            .satisfies(a -> assertThat(a.getBillingAddress()).as("check billingAddress").isEqualTo(expected.getBillingAddress()));
    }
}
