package com.paragon.project1.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class WishlistAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWishlistAllPropertiesEquals(Wishlist expected, Wishlist actual) {
        assertWishlistAutoGeneratedPropertiesEquals(expected, actual);
        assertWishlistAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWishlistAllUpdatablePropertiesEquals(Wishlist expected, Wishlist actual) {
        assertWishlistUpdatableFieldsEquals(expected, actual);
        assertWishlistUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWishlistAutoGeneratedPropertiesEquals(Wishlist expected, Wishlist actual) {
        assertThat(actual)
            .as("Verify Wishlist auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWishlistUpdatableFieldsEquals(Wishlist expected, Wishlist actual) {
        assertThat(actual)
            .as("Verify Wishlist relevant properties")
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWishlistUpdatableRelationshipsEquals(Wishlist expected, Wishlist actual) {
        assertThat(actual)
            .as("Verify Wishlist relationships")
            .satisfies(a -> assertThat(a.getProducts()).as("check products").isEqualTo(expected.getProducts()));
    }
}
